### PR TITLE
Update string_manipulation.jl

### PR DESCRIPTION
**Pull request by arm61**
Remove parentheses around inline for iteration.

### CODE REVIEW

**Comment by samuelcolvin** [comment]
why closed?

**Comment by arm61** [comment]
Failed travis (apparently at the io.jl level), realised it would be more helpful to work through the how tutorial and fix any other bugs discovered (not to imply the examples are buggy :) )

**Comment by samuelcolvin** [comment]
The examples are pretty buggy because they're old.

They all need updating.

**Comment by arm61** [comment]
I am enjoying working through them so will try and fix anything I can along the way and send a pr then :)

**Comment by samuelcolvin** [comment]
Great, promise to review and merge PRs and deploy an update.

**Pull request closed without merging**
