### PR TITLE
[WIP] Update code&links to Julia 1.0

### LINKED ISSUE #25: Example not compatible with v1.0
https://github.com/samuelcolvin/JuliaByExample/blob/4442c151be5ac039172a4d800634b5aa7e687adb/src/functions.jl#L26
Apparently you need to include "using Printf" for this to work in v1.0.

(I just started using Julia so I'm no expert. Just wanted to give a note.)

### LINKED ISSUE #27: Julia 1.0 - Converting
> JuliaByExample/src/formatting_converting_strings.jl

```
e = float(e_str1)
```

> ERROR: LoadError: MethodError: no method matching AbstractFloat(::String)

Line 3 can not convert String to Float...

### PR DESCRIPTION
**Pull request by inkydragon**
- [x] All example code test in Julia v"1.0.0" without any warning or error;
- [x] All doc links point to docs.julialang@v1.0.0;
- [x] All links use https;
- [x] Update `addcomments.jl`;
- [x] Update comments with the output of the code;
- [x] Update `.travis.yml` if need;
- [x] Build & Check output website.

fix #25 , fix #27

### CODE REVIEW

**Comment by XVilka** [comment]
@samuelcolvin ping?

**Comment by samuelcolvin** [comment]
Sorry the project is slightly abandoned.

I'll try and merge and deploy next week.

**Comment by XVilka** [comment]
@samuelcolvin can you please check this PR again?

**Comment by samuelcolvin** [comment]
Hi @XVilka, sorry for the slow response.

I'm not writing any julia at the moment and pretty busy with other open source projects.

Is there any change you could get tests to pass? The problem seems to be with the "winston" plotting package.

**Comment by XVilka** [comment]
Maybe it makes sense to update to Julia 1.2.0? Pure 1.0.0 is quite old, and there were some improvements since.

**Comment by inkydragon** [comment]
> Pure 1.0.0 is quite old

v1.0.5 is Long-term support version. We just need to wait until next LTS version comes out.
And I thinks most of those code works well in 1.2.0, maybe some pkg will fail.

**Comment by samuelcolvin** [comment]
thank you very much. I'll try and get the new version deployed soon.

**Comment by samuelcolvin** [comment]
tests fixed and deployed. From now on the site can simply be deployed by merging to master, making changes much easier.

**Pull request merged**
